PORTNAME=	spirv-headers
DISTVERSIONPREFIX=	vulkan-sdk-
DISTVERSION=	1.4.357.0
CATEGORIES=	graphics

MAINTAINER=	yuri@FreeBSD.org
COMMENT=	Machine-readable files for the SPIR-V Registry
WWW=		https://github.com/KhronosGroup/SPIRV-Headers

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake

USE_GITHUB=	yes
GH_ACCOUNT=	KhronosGroup
GH_PROJECT=	SPIRV-Headers
GH_TAGNAME= 29981f65241605e08b0ede4cfeb999fe3b723c6a

NO_ARCH=	yes

.include <bsd.port.mk>
