# Created by: Yuri Victorovich <yuri@rawbw.com>
# $FreeBSD$

PORTNAME=	pybind11
DISTVERSION=	2.6.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@FreeBSD.org
COMMENT=	Seamless interoperability between C++11 and Python

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes
#USES=		cmake gmake python:2 compiler:c++11-lib
#CMAKE_ARGS+=	-DPYBIND11_INSTALL=ON -DPYBIND11_TEST=OFF

.include <bsd.port.mk>
