--- pyproject.toml.orig	2026-06-28 07:54:47 UTC
+++ pyproject.toml
@@ -8,7 +8,7 @@ requires = [
     "Cython>3.1.0,<4.0.0a0",  # Note: sync with setup.py, environment.yml and asv.conf.json
     # Force numpy higher than 2.0, so that built wheels are compatible
     # with both numpy 1 and 2
-    "numpy>=2.0.0",
+    "numpy",
     "versioneer[toml]"
 ]
 
@@ -27,9 +27,9 @@ dependencies = [
 license = {file = 'LICENSE'}
 requires-python = '>=3.11'
 dependencies = [
-  "numpy>=1.26.0; python_version < '3.14'",
+  "numpy; python_version < '3.14'",
   # Earlier versions of NumPy are fundamentally broken on 3.14
-  "numpy>=2.3.3; python_version >= '3.14'",
+  "numpy; python_version >= '3.14'",
   "python-dateutil>=2.8.2",
   "tzdata; sys_platform == 'win32'",
   # Emscripten is the platform system for Pyodide.
